name: Daily Trading Run

on:
  schedule:
    # 20:05 UTC Mon–Fri (after US market close). Adjust if needed.
    - cron: "5 20 * * 1-5"
  workflow_dispatch: {}  # allow manual runs

permissions:
  contents: write

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run trading script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python trading_script.py

      - name: Build GitHub Pages (docs/)
        run: |
          python tools/build_pages.py || echo "No pages built yet"

      - name: Diagnose file changes
        run: |
          echo "---- git status BEFORE heartbeat ----"
          git status
          echo "---- recently modified files ----"
          ls -lt | head -n 20 || true
          echo "---- diff summary ----"
          git diff --name-only || true

      - name: Heartbeat (guarantee a change to commit)
        run: |
          mkdir -p docs
          date -u +"%Y-%m-%d %H:%M:%S UTC" > docs/last-run.txt
          echo "Updated docs/last-run.txt"

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: workflow run (heartbeat + outputs) [skip ci]"
            git push
          fi
